atomic

host: Don't rollback with --status

---

COPYING
atomic

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

Use updated FSF address

---

README.md

Small text changes. Nothing major. Also stealing some of this for the Project Atomic site.

A few minor changes

---

atomic

It will comply with design doc.
Use case:
https://github.com/rvykydal/dockerfile-iscsid/tree/master/rhel7

For running background container run command if specified.

---

README.md

fixed a tiny typo

---

docs/install/Fedora.md

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

Adding the install/build steps for Fedora

---

atomic

Fix bug with non init variable.

Fix upload

---

.gitignore
Atomic/atomic.py
Makefile
atomic
atomic_client.py
atomic_server.py
org.atomic.conf
org.atomic.policy
org.atomic.service

Added support for version and verify to return dbus data to caller, had to change CLI tools to use different functions to get printable data.
Also moved Atomic Class to atomic.py in the library.

Add dbus support for version and verify

---

README.md

I assume that is a typo and not some magic that escapes me.

use NAME and IMAGE variables, not literals in README.md

---

Atomic/atomic.py
atomic

See https://lists.projectatomic.io/projectatomic-archives/atomic/2015-June/msg00000.html
for an example use case.

host: Proxy the `rpm-ostree rebase` operation too

---

Makefile
atomic_dbus.py
org.atomic.service
setup.py

Also cleanup setup.py to handle most of the setup.
setup handles python3 issues better then standard Makefile

Rename atomic_server.py to atomic_dbus.py

---

bash/atomic
docs/atomic-images.1.md

Added a simple completion script for atomic images, and made some minor changes to the manual page.

Atomic images completions and man-page changes

---

Atomic/atomic.py

Correcting the typo error change self.default_uid to default_uid
There is no self.default_uid
@rhatdan

modify self.default_uid to default_uid

---

atomic.sh
atomic.sysconfig

Small tweaks to make command forwarding work properly.

atomic.sh: fix up command forwarding to rhel-tools

---

Atomic/atomic.py
atomic
bash/atomic
docs/atomic-install.1.md
docs/atomic-run.1.md
test.sh
tests/integration/test_display.sh
tests/test-images/Dockerfile.1

Signed-off-by: Sally O'Malley <somalley@redhat.com>

WIP: Add --display to run|install

---

docs/atomic-mount.1.md
docs/atomic-stop.1.md
docs/atomic-uninstall.1.md

docs: fix typos

---

Atomic/__init__.py
Atomic/atomic.py
Atomic/config.py
Atomic/pulp.py
atomic
atomic_client.py
atomic_dbus.py
setup.py
tests/unit/test_mount.py

Cleanup of python codebase to be compliant with [PEP8](https://www.python.org/dev/peps/pep-0008/), the style guide for python code, according to the `pep8` python code linter.

PEP8 (Python style guide) Compliance

---

Atomic/__init__.py
Atomic/atomic.py
Atomic/mount.py
Atomic/pulp.py
atomic
atomic_dbus.py

Fixes https://github.com/projectatomic/atomic/issues/115

Fixes pep8 warnings for python modules

---

docs/atomic-host.1.md
docs/atomic-images.1.md
docs/atomic-info.1.md
docs/atomic-install.1.md
docs/atomic-run.1.md
docs/atomic-stop.1.md
docs/atomic-uninstall.1.md
docs/atomic-update.1.md
docs/atomic-upload.1.md
docs/atomic-verify.1.md
docs/atomic-version.1.md
docs/atomic.1.md

Signed-off-by: Sally O'Malley <somalley@redhat.com>

atomic man fixes

---

Atomic/mount.py

don't fail when dead images are around

---

docs/atomic-update.1.md

Signed-off-by: Sally O'Malley <somalley@redhat.com>

typo atomic-update.1.md

---

Atomic/satellite_new.py

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

resolve syntax error and use python3 friendly print

---

Atomic/atomic.py
Atomic/util.py

When an atomic scan is called without --detail, we print the name
of the container or image if that is provided.  Prior, we only
printed the first 12 characters of the image or container ID.  We
also no dynamically size the left-most column of the output, which
can accomodate various lengths of the image or container names.
Created a common input parser for when the user input.  So if a
user inputs a partial name, we attempt to discern the actual
container or image being referenced.  The were three definitions
added; _is_container, _is_image, and a wrapper function for both
called get_input_id.  If either function can make a match to the
input identifier, it returns the image or container ID.
And lastly, to reduce the number of calls (queries) into docker,
there are now stub functions …

Improve scan out and common input parsing

---

atomic

atomic: fix a typo

---

Atomic/__init__.py
setup.py

setup.py: egg files are hard to debug and working with,
espicially on a platform like Atomic.

Do not build atomic with an egg file

---

Atomic/__init__.py
CHANGELOG.md

Bump version to 1.7

---

atomic

Group all identical exception handling in a single block.
Signed-off-by: Cleber Rosa <crosa@redhat.com>

atomic: simplify exception handling

---

Atomic/Export.py
Atomic/Import.py
Atomic/atomic.py
Atomic/mount.py
atomic

Adding to fix https://github.com/projectatomic/atomic/issues/165

Exit atomic if not run as root

---

Atomic/diff.py

This reverses my previous patch

I merged Colins patch instead of mine

---

Atomic/atomic.py

In response to BZ #1285461, we now dynamically
set the maximum length for the repository and
tag fields to assure the output will line up
for more information.

    RFE: Align output for atomic images (1285461)

---

Atomic/diff.py

Under the condition that you diff two images and one or both
of the images are not RPM based, no cleanup of the mounts and
dm devices was done. This was reported via BZ #1285006.
We now handle the exit and cleanup differently which counts
for this condition.

BUGFIX: Atomic diff leaks FD (BZ # 1285006)

---

docs/atomic-top.1.md

The man page for atomic top was accidently not commited in the
PR.

Atomic Top Man

---

Atomic/mount.py

Correcting a bug observed by the openscap team where under
certain conditions, the deletion of a temporary image would
cause a traceback when noprune=False.
Added a loop with timeout for unmounting by path to prevent
race failures between openscap, docker, the filesystem, and/or
dms.

Add noprune to image deletion

---

Atomic/verify.py

python3 changed the interator .next() to __next__()
Cleanup handling of local_nvr

Code cleanup and port for python3

---

atomic_dbus.py
migrate.sh

In preparation for moving the tester to F23, some fixes are needed to get the current master to pass cleanly.

F23 tweaks

---

Atomic/atomic.py
Atomic/top.py
atomic
bash/atomic
docs/atomic-top.1.md
tests/integration/test_diff.sh
tests/integration/test_top.sh

Basic tests for atomic diff and top which should catch
basic code regressions.

Add tests for Atomic diff and top

---

Atomic/Export.py
Atomic/atomic.py
Atomic/mount.py
Atomic/top.py
Atomic/util.py

Utilize the docker environment variables for non-local
daemons

Use DOCKER_* environment variables

---

docs/install/Debian.md
docs/install/Fedora.md

Updating install documents to conform to Atomic 1.8

---

Atomic/Export.py
migrate.sh
tests/integration/test_migrate.sh

Fix atomic migrate test

---

Atomic/Import.py

atomic migrate import cleanup

---

tests/integration/test_migrate.sh

This patch does two things:
1. Add a validation step after migration to make sure that the
containers and images were indeed migrated.
2. Don't actually change the docker configuration to use overlayfs,
which currently causes issues on e.g. Fedora kernels. This has
been the source of the instability of the PR tester. It can be
reproduced locally by running:
```
```
We can uncomment out that block once the workaround for it has
made it to the stable kernels. See the comment block for more
details.

test_migrate.sh: validate and don't use overlayfs

---

Atomic/atomic.py

The async API has several advantages, namely:
- it doesn't take over the dbus message queue of openscap-daemon,
other users can still query it and interact with it
- it allows better scheduling in the daemon itself, daemon will
limit the amount of concurrent work
- in the future it will be possible to cancel the work (CTRL+C),
the change in atomic already does everything necessary, this
only needs to be fixed in the daemon
In case the user has an older version of openscap-daemon we fallback to
the old synchronous API with huge timeout.
You need openscap-daemon from the git repository or 0.1.1 when it gets released to use the async API.
**I haven't tested this as much as I normally would, am in a hurry this Friday. Hopefully everything works, the implementation is very similar to …

Use the async API from openscap-daemon to perform CVE scans if possible

---

migrate.sh

Bugzilla: 1284877: fixes run/gotar issue

---

migrate.sh

atomic migrate: Add support for docker 1.10

---

Atomic/atomic.py
Atomic/run.py

This actually calls the function to setup the environment.

We are not calling self.cmd_env just passing the function

---

tests/integration/test_migrate.sh

disable test_migrate.sh for atomic migrate command

---

tests/integration/test_verify.sh

I forgot to add the actual test script in my
previous commit. Apologies.

test_verify.sh: Actually add the file

---

Atomic/diff.py
Atomic/top.py

Atomic top was broken when you passed it valid container names
or ids.  This is now fixed plus added a simple check for validate
that the names or ids are correct.
This addresses https://github.com/projectatomic/atomic/issues/314

Atomic/top.py - Fix when specifying container names or ids

---

Atomic/Export.py
Atomic/Import.py
Atomic/atomic.py
Atomic/run.py
Atomic/util.py
atomic
atomic.conf
bash/atomic

This will allow us to support docker-latest

Allow user to specify alternative docker executables.

---

Atomic/scan.py

Discovered a bug that revealed SELinux was preventing a proper
bind mount for /scanout.  Added ':rw,Z' to the docker command
used to launch scanners.
Also, altered the DEBUG bool to more appropriately use the
atomic --debug bool.

Atomic/scan.py SELinux prevents bind mounting

---

atomic_dbus.py

atomic_dbus: fix undefined variable

---

Atomic/scan.py
atomic_client.py
atomic_dbus.py

Will return a dictionary of all necessary information pertaining to scanners configured in the system.

Scan list changes

---

Atomic/Export.py
Atomic/Import.py
Atomic/atomic.py
Atomic/delete.py
Atomic/diff.py
Atomic/mount.py
Atomic/pulp.py
Atomic/satellite.py
Atomic/util.py
atomic

Normalize encoding of output to stdout and stderr
Signed-off-by: Jhon Honce <jhonce@redhat.com>

Refactor to use util.write_* functions

---

Atomic/trust.py
bash/atomic
docs/atomic-trust.1.md
tests/unit/test_trust.py

remove sigstore config with trust delete

---

.redhat-ci.sh
.redhat-ci.yml

We have plenty of disk space here. So let's give the root LV a bit more
so that some of our new tests can run properly.

.redhat-ci.sh: resize root LV

---

Atomic/__init__.py

Signed-off-by: baude <bbaude@redhat.com>
-
-
-
-
If your Pull request contains new features or functions, tests are required. If the PR is a bug fix and no tests exist, please consider adding some to prevent regressions.

Bump to V1.21.1
