projectatomic/atomic

atomic
This allows matching the existing model for /usr/bin/rpm-ostree:
- atomic upgrade -r
- atomic status
etc.
=> host: Use subparsers rather than arguments

atomic
Thanks to http://stackoverflow.com/questions/4042452/display-help-message-with-python-argparse-when-script-is-called-without-any-argu
=> atomic: Print help by default if no arguments supplied

atomic
After pulling the rheltools image, I tried to perform `atomic install` on it to see what happened
```
$ sudo docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
rhel-tools-docker-7.1-1   latest              a2893926ea0f        6 hours ago         850.9 MB
[cloud-user@atomic-20150125 ~]$ sudo /usr/local/bin/atomic install rhel-tools-docker-7.1-1
Traceback (most recent call last):
File "/usr/local/bin/atomic", line 396, in <module>
sys.exit(args.func())
File "/usr/local/bin/atomic", line 274, in install
return(subprocess.check_call(cmd, env={
UnboundLocalError: local variable 'cmd' referenced before assignment
```
I think this commit should fix that error.
=> Fix error when image already exists with Labels

atomic
Fixes `atomic run rhel7 echo hello` - an image without any metadata.
=> Add an internal helper for config retrieval that handles no-config

Makefile
Neither "make" or "make install" should not run tests.  Further,
change the default target to be "all" by listing it first.
=> build: "all" should be default, don't run tests on install

atomic
(Note, only lightly tested - the test suite is failing for me right now even without this patch, due to what I think is the automatic prefixing with `docker.io` for images)
If the docker client output enough stderr, we'd end up with a
deadlock.  I think the original idea here was to suppress error
messages - if so, /dev/null works.  Perhaps in the future though we
should store the error buffer somewhere in case it is needed.
=> Redirect stderr to /dev/null instead of creating an unread pipe

atomic, atomicpulp/__init__.py, atomicpulp/config.py, atomicpulp/pulp.py, setup.py
This patch will allow users to upload to either a docker registry or
to a pulp crane server.  We want to support Sattelite in the future as
well.
Will read authorization data out of ~/.pulp/admin.conf if it exists, otherwise
it will prompt for Username and Password.
=> Add ability to upload/push to a registry

atomic
The run and install commands were not seeing the environment, this will
allow users to pass environment variables into atomic commands.
=> When running atomic commands we need to pass the users environment

atomic, bash/atomic, docs/atomic-verify.1.md, docs/atomic-version.1.md
Want to be able to display atomic version including layers ID, NAME:VERSION:RELEASE Repository/Tag
Will also display recursively all layers in the image.
atomic version test
afecc5f6a3c4d8f2326901c94cdf84aab0890ea827c38f2b0d2e2a4ba5ace7d6 Apache:1.0:1 test:latest
Another feature I have added is, the ability to recurse though all of the layers of the image.
atomic version -r test
afecc5f6a3c4d8f2326901c94cdf84aab0890ea827c38f2b0d2e2a4ba5ace7d6 Apache:1.0:1 test:latest
21b2d6e4171b024cb48bb2d02d626481e37724a6e03dac7962e44cc8612fbf22 Apache:1.0:1
83202d54cf27439381b3d668d02f3a21cb75ebba4623d86e1fdbad614660424e Apache:1.0:1
90ff7403d883c0ccde72bf630cb77e224fd6b517fc4b61b84f8d9739dab93c9f Apache:1.0:1
12f19f77bc52483d902727b6c142f20cc79109ad45e36869f30c15228534eb5b Apache:1.0:1 …
=> Add additional support for atomic version

Atomic/atomic.py, atomic
We are working on the labeling standard, and one of the things that has come up
is a discussion on what case the labels should be Uppercase, Lowercase, or capatalized
This patch will match all three.
Also fix a couple of small bugs
=> Handle labels with different cases

Atomic/atomic.py, atomic, docs/atomic-install.1.md, docs/atomic-uninstall.1.md
This patch will allow a user to pass additional arguments to the command specified in the INSTALL/UNINSTALL lines
=> Pass additional arguments to the atomic install/uninstall line

Atomic/pulp.py
Fixes a crash when `atomic` is deployed with current RHEL.
=> pulp: Hack around python-requests/urllib3 being different in Fedora/RHEL

Atomic/atomic.py, Atomic/mount.py, atomic, bash/atomic, docs/atomic-mount.1.md, docs/atomic-unmount.1.md, docs/atomic.1.md, test.sh
CLI integration with python docker_mount module provided by @baude. This PR includes PR#60 (and docker_mount.py here is more up-to-date than the one in PR#60).
Mount a container image via `atomic mount repo/image[:tag] /path/to/mountpoint`, unmount via `atomic unmount /path/to/mountpoint`
Would like thoughts on how to eliminate the required repo in the image name, I would think that `atomic mount fedora /mnt` would be valid syntax. Not sure how to check the registries (or how to prioritize registries with identically named images)
=> Basic atomic mount/unmount commands

Atomic/atomic.py, docs/atomic-install.1.md, docs/atomic-run.1.md, docs/atomic-stop.1.md, docs/atomic-uninstall.1.md, test.sh
This commit adds `IMAGE` and `NAME` as environment variables
passed to install, uninstall, stop, and run (similarly to
`CONFDIR`, `DATADIR`, and `LOGDIR`).  This allows users to write
`NAME=${NAME}` instead of `NAME=NAME`, and also enables `${NAME}`
and `${IMAGE}` to be used in arbitrary parts of the commands.
This commit is based off of ideas from #59
=> Add IMAGE and NAME as environment variables

Atomic/atomic.py, Atomic/mount.py, Atomic/util.py, atomic, bash/atomic, docs/atomic-mount.1.md
Changes:
- Added --live option to mount running containers. Default behavior is to mount *snapshots*, rather than live.
- Refactored to avoid creating new thin devices. Now we just use docker's or create identical ones.
- By default image-mounts create a container tagged with a sentinel environment variable.
- Non-live container mounts commit the container to an image (tagged with a sentinel label) then image-mount it. On cleanup, the container mounted at the mount path and its image are inspected for sentinel values and removed if they are tagged.
- a --no-bind option was added to prevent atomic mount from bind-mounting 'mntpoint/rootfs' to 'mntpoint'. The default behavior is to perform the bind-mount.
- More easily support extension to other backends. e.g. to support the btrfs backend, …
=> atomic mount --live (and other improvements)

Atomic/mount.py, docs/atomic-mount.1.md
There is a bug in the atomic cli which prevents users who do not have the GraphDriver API exposure patch from mounting containers. This patch fixes that issue.
In addition, it also fixes a but in mount options in such a way that default options will be honored only if no mount options are provided. The old logic was cumbersome, and would have been prohibitive of any other Graphdriver backend having its own set of default options. The man pages have been updated to reflect the simpler behavior.
=> Bugfix atomic CLI for users without GraphDriver API exposure, simpler mount options

Atomic/atomic.py, README.md, docs/atomic-install.1.md, docs/atomic-run.1.md, docs/atomic-stop.1.md, docs/atomic-uninstall.1.md
These substitutions are useful with docker -u SUDO_UID:SUDO_GID ...
for userspace tools such as format translators
=> Add SUDO_UID and SUDO_GID variable substitions

Atomic/atomic.py, atomic, docs/atomic-install.1.md, docs/atomic-run.1.md, docs/atomic-uninstall.1.md
@rhatdan 
The Labels look like below.
LABEL RUN  docker run -it --rm \${OPT1} --privileged -v `pwd`:/atomicapp -v /run:/run -v /:/host --net=host --name \${NAME} -e NAME=\${NAME} -e IMAGE=\${IMAGE} \${IMAGE} -v \${OPT2} run \${OPT3} /atomicapp
LABEL STOP docker run -it --rm \${OPT1} --privileged -v `pwd`:/atomicapp -v /run:/run -v /:/host --net=host --name \${NAME} -e NAME=\${NAME} -e IMAGE=\${IMAGE} \${IMAGE} -v \${OPT2} stop \${OPT3} /atomicapp
LABEL INSTALL docker run -it --rm \${OPT1} --privileged -v `pwd`:/atomicapp -v /run:/run  --name \${NAME} -e NAME=\${NAME} -e IMAGE=\${IMAGE} \${IMAGE} -v \${OPT2} install \${OPT3} --destination /atomicapp /application-entity
Usage:
atomic --opt1="-p :5000" --opt2="-d" install submod/guestbookphp-app
=> Support OPT1, OPT2 in install/run command

atomic
I got docker to merge a similar request to this.   We should follow suit.
Problem with printing usage message is it can cause confusion to the user.
ls --foobar 
ls: unrecognized option '--foobar'
Try 'ls --help' for more information.
=> Atomic should print error message only not usage on error

README.md
BindTo=docker.service ensures, that the service is stopped or restarted
whenever docker is. This is more sane behavior if no docker restart policy is
given (i.e. --restart=always).
=> BindTo docker in example systemd service

Atomic/atomic.py, atomic, docs/atomic-images.1.md
This patch set adds the images keyword.  This will list all local
images by default.
You can also use the --prune option to delete any dangling images,
freeing up disk space.
In the future we would like to expand to support other frameworks
besides docker to list any other local container images.
=> Add support for listing images for atomic

atomic
gettext.install() has changed between Python 2 and 3 and no longer has
an argument called unicode. This is handled by a try-except when the code
is executed, but pylint doesn't know that. By adding this comment, it will
stop reporting it as an error.
=> Tell pylint to ignore unexpected-keyword-arg

atomic.sysconfig
We leave it up to each distro to configure the TOOLSIMG to be used.
Related PR: https://github.com/projectatomic/atomic/pull/91
=> atomic.sysconfig: leave default TOOLSIMG undefined

Atomic/mount.py
In docker API version 1.19, mem_limit was moved to the host_config section of the container metadata. This changed the docker-py api and attempts to mount an image or non-live container would result in the following error:
`mem_limit has been moved to host_config in API version 1.19`
This patch addresses the problem by removing the memory limit, which was probably unnecessary in the first place, as these containers are only temporary for the purposes of mounting the internal filesystems.
=> Bugfix for docker create_container API change.

Atomic/atomic.py, Atomic/util.py, atomic, docs/atomic-info.1.md, test.sh, tests/integration/test_info.sh, tests/integration/test_mount.sh, tests/integration_template.sh
Rather than pull a repository when it isn't found locally, with this patch the `atomic info` command will now use remote inspection. It will first attempt to find the image locally, and then will query configured registries.
Additionally, a `--remote` flag will force `atomic info` to use only remote repositories.
While writing tests for this feature, I also changed the invocation of `atomic` in the test harness. As a result, the test harness is now capable of including the CLI integration tests in the coverage report.
Tested against `rhatdan/docker:fedora-1.7`
=> Integrate remote inspection with Atomic info.

test.sh, tests/integration/test_info.sh, tests/unit/test_util.py
This patch will allow arbitrary files to be inserted into the test images.
If you have a file hierarchy that looks like this:
- test-images/
- Dockerfile.\<id\>
- Dockerfile.\<id\>.d/
- foo
Then the directory `Dockerfile.<id>.d` will be available to the image at build time, and can be added to the image, e.g. (with an \<id\> of 'foo') as
`Dockerfile.foo`:
```
FROM rhel7:7.1-9
MAINTAINER "William Temple <wtemple at redhat dot com>"
ADD ./Dockerfile.foo.d/some_script.sh /usr/bin/some_script
RUN "chmod +x /usr/bin/some_script"
```
The script will also now rebuild any test-images whose files have changed.
@rhatdan RFC. I think this is the cleanest way to add arbitrary files to these test images.
@sallyom This should enable you to add scripts/etc. to the test images, and you should then be …
=> Allow arbitrary files in test images.

Atomic/mount.py, tests/integration/test_info.sh
Bugfix for atomic mount not detecting the correct docker thin-pool device prefix and failing to recognize containers mounted as docker containers. Also changed test_info.sh to use CentOS rather than RHEL images, as the test harness was changed to ensure that the test environment contains a CentOS image, but not necessarily a RHEL image.
=> Bugfix atomic mount command & incorrect test configuration

Atomic/atomic.py
The size_name tuple missed "B" bytes unit option in convert_size(),
and the output of images are not good if the REPOSITORY name is
a little long such as registry.access.redhat.com/rhel7, it looks
like this:
```shell
REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker-dev                master              bffd816efbfe        2015-06-09 18:15    1.58 TB
*<none>                    <none>              3439600f6aa8        2015-06-09 17:39    188.31 GB
*<none>                    <none>              8df315cf193a        2015-06-09 17:24    188.31 GB
docker.io/ubuntu          14.04               fa81ed084842        2015-06-01 08:00    188.28 GB
docker.io/busybox         latest              8c2e06607696        2015-04-18 06:01    2.43 GB …
```
=> atomic: add missing bytes unit

Atomic/atomic.py
atomic install with --display doestn't work, and atomic run still preview the command without --display option, the patch will fix them.
=> atomic: fix errors in display option

Atomic/atomic.py, atomic
We have two cases when calling atomic run, In one case the container
exists and we will just execute the COMMAND into the container.
If the container is not running, we want to append the COMMAND onto the
container RUN method, to allow more complex interaction.
For example if i had container image TEST that had the run label:
LABEL RUN="docker run -ti \${IMAGE} command"
atomic run TEST -h
Would execute
docker run -ti \${IMAGE} command -h
Displaying help information about the container.
=> Append command to container run method when container is not running.

requirements.txt, setup.py
Fixes #112 
- Access ``setup.py`` without installing dependencies
- Make ``python setup.py`` develop work.
- Install python dependencies from ``requirements.txt`` on running ``setup.py {develop,install}``
- Fix linting errors
=> Fix setup py (fixes #112)

setup.py
The earlier 58a6e0e4eff379578d497d67002cbef1438f8ab2 and later
455fc8499fee1b970eafd7f80942405ef6bef17f both break if the atomic
package is not actually installed on the system - as will be the case
with `mock/pbuilder` style builds.
It looks like OpenStack uses https://pypi.python.org/pypi/pbr which
presumably solves this problem.  I however am not super interested
right now in diving into that...I just want the thing to build.
So let's just hardcode the version number in two places for now.
Anyone who wants to improve this should probably look at PBR or
something other projects do.
=> build-sys: Avoid self-dependency in setup.py

docs/atomic-install.1.md, docs/atomic-uninstall.1.md
Because it is error prone to use it this way. Using the same NAME in the
environment variable -e NAME=\${NAME} and in container name (--name) for
install and uninstall seems incorrect because both of them serve
different purposes. Also if NAME is being used to create a container in
the install script, which happens most of the time, it leads to failure
because the same NAME is used for the ephemeral container to process
LABEL INSTALL and due to that, the actual container can not be created
and it gives following error:
"Error response from daemon: Conflict. The name "etcd1" is
already in use by container b50ea8bf1d40."
Anyway assigning names (using -name NAME) to ephemeral containers during
install and uninstall does not make much sense in my point of view.
=> Removes --name \${NAME} from atomic install and uninstall man pages

Atomic/satellite.py
I caught a bug in satellite.py where there was extra whitespace in one of the upload calls, which broke the call.
Signed-off-by: jramseye <jramseye@redhat.com>
=> Fixing a whitespace bug in satellite.py

Atomic/mount.py
```
Traceback (most recent call last):
File "/usr/bin/atomic", line 306, in <module>
sys.exit(args.func())
File "/usr/lib/python3.4/site-packages/Atomic/atomic.py", line 705, in mount
self.args.live).mount(self.args.image, options)
File "/usr/lib/python3.4/site-packages/Atomic/mount.py", line 268, in mount
driver_mount_fn(identifier, options)
File "/usr/lib/python3.4/site-packages/Atomic/mount.py", line 384, in _mount_overlay
status.stderr)
TypeError: Can't convert 'bytes' object to str implicitly
```
=> mount,overlay: fix tback when mount fails

docs/install/Debian.md, requirements.txt
fixes #135 
* changes requirements to fit default python pip install of `requests`
* added tutorial doc on how to install atomic to debian (tested environment debian 8)
=> added debian install support and doc

Atomic/__init__.py, setup.py
This fixes version info resolution during using setup.py with deps installed and version resolution from ``Atomic/__init__.py`` too. This is in response to https://github.com/projectatomic/atomic/issues/112#issuecomment-134492154
=> Resolve version info from setup.py using pkg_resources.

Atomic/atomic.py
There is a chance that we could crash if default_uid is not initialized
=> Must setup default_uid

Atomic/atomic.py
changes echo location from `/usr/bin/echo` to `/bin/echo`
fixes issue #139
=> make echo cross-distro

Atomic/atomic.py, tests/integration/test_display.sh, tests/integration/test_info.sh
Fix test failures that have crept into the atomic master.
tests/integration/test_display.sh
Fix failure related to defined UID/GID's in the test itself.  I now
use sed to remove the --user UID:GID to make the comparison equal
and remove potential for dynamic failures.
I also had to add a conditional if the labels (in python) are of
type None to prevent a traceback.
tests/integration/test_info.sh
There seemed to be two related failures in the test case that relate to
running 'atomic info --remote'.  If that command is run with a docker
daemon that is not capable of --remote, the test will failure.  I added
a variable based on the return of that command and put it under the
set +e section.
I then added a conditional for that test (based on the return of above),
to only run the test if the …
=> FIX test failures

Atomic/mount.py
* Add mnt_mkdir keyword arg (bool) to the DockerMount class
to indicate we want to use the mountpoint as a basedir and
create temporary dirs there for mounting.  This fits the
API model so things like the image-scanner and friends
can leverage this code.
* Small changes to DockerMount.mount and cleanup to account
for this change.  Also return the new path when the mount
function is called.
=>     Atomic/mount.py

atomic
It's introduced by formatting codes then forget to delete old codes,
the atomic help looks like this.
version             display image 'Name Version Release' label
version             display image 'Name Version Release' label
=> Atomic: delete duplicate command from atomic help document

Atomic/atomic.py, Atomic/mount.py, Atomic/util.py, atomic, docs/atomic-scan.1.md
Add the ability to scan a container or image leveraging
a containerized version of the openscap-daemon and atomic.
i.e. atomic scan image_id
=> atomic - Add CVE scan atomic

Atomic/atomic.py, README.md, docs/atomic-install.1.md, docs/atomic-uninstall.1.md
Users can do this themselves by using the ${NAME} field.
Hard coding behaviour of these three variables was a mistake, and this
is a lot more flexible.  I could add back the variables and don't document them
if people think someone has used them
=> Remove automatic setting of CONFDIR, DATADIR and LOGDIR

Atomic/atomic.py, Atomic/util.py
Most sub-commands in atomic require the user to enter
some sort of valid input name.  This can typically be:
* container name or container ID
* an image ID
* some portion of the name of the image as derived
by the repo-tags
We know have a common function that can verify if the input
is valid.  It will return the container ID or image ID if
the image is valid.  This leverages the current
util.image_by_name function as well as three additional
functions that help derive container and image IDs.
=> Verify inputs are valid

tests/integration/test_display.sh, tests/test-images/Dockerfile.1
This patch makes test_display.sh pass. They are mostly tweaks to account
for the following:
- Account for commit 7858957, which removes {CONF,LOG,DATA}DIR from the
target environment.
- Account for commit ae931d0, which removes those default bind mounts.
- Fix a few mismatches between the labels in the Dockerfile vs the
expected output in the test script.
And with that, all tests (should) pass!
=> Make test_display.sh pass again

Atomic/__init__.py, Atomic/atomic.py, Atomic/satellite_new.py, Atomic/util.py, Makefile, atomic
The `pylint` invocation in the `Makefile` was only scanning the `atomic` file. We now make it scan all the python files. The following commits fix all the new issues that `pylint` detected.
The final commit fixes the way `rpm-ostree` args are passed to avoid a TypeError during runtime.
=> Make pylint scan all the python files and fix pylint issues

atomic, docs/atomic-install.1.md, docs/atomic-run.1.md, docs/atomic-uninstall.1.md
opt1, opt2 and opt3 can be specified as environment variables.
OPT1=--debug atomic install foobar
No reason to have options.
=> Remove opt documentation, but continue support

Atomic/atomic.py
Previously it failed with:
`too many values to unpack (expected 2)`
=> Atomic.images(): handle 'localhost:5000/test-image:latest'

docs/atomic-stop.1.md
`docker kill` doesn't support a `--name` flag, just container name/id
directly.
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1259829
Signed-off-by: Antonio Murdaca <amurdaca@redhat.com>
=> docs: atomic-stop.1.md: remove `--name` flag from example

Atomic/__init__.py, setup.py
This is a re-commit of 106878815f5a5dd61b0e527c502fb6eeaf0c9c67
because the later fix in #112 added a *runtime* dependency on
setuptools, which we don't want.
It looks like OpenStack uses https://pypi.python.org/pypi/pbr which
presumably solves this problem.  I however am not super interested
right now in diving into that...I just want the thing to build.
Ansible just inserts the current dir in `sys.path`, which seems like a
simple hack, so let's do that.
Conflicts:
setup.py
=> Drop use of setuptools as it injects a runtime dependency

Makefile
The `python-build` target lists `atomic` as a prerequisite target.
However, there is no explicit target named 'atomic', so `make` tries to
find any implicit rules that apply. One of the rules that it tries is
whether the unprocessed file is called `atomic.sh`. Since that file
exists, it proceeds by copying `atomic.sh` to `atomic` if e.g.
`atomic.sh` is newer than `atomic`:
Considering target file 'python-build'.
File 'python-build' does not exist.
Considering target file 'atomic'.
<snip>
Found an implicit rule for 'atomic'.
Considering target file 'atomic.sh'.
<snip>
Finished prerequisites of target file 'atomic.sh'.
No need to remake target 'atomic.sh'.
Finished prerequisites of target file 'atomic'.
Prerequisite 'atomic.sh' is newer than target 'atomic'.
Must remake target 'atomic'.
cat …
=> Makefile: remove atomic target

Makefile
Also added a touch invocation to allow users to do:
`GO_MD2MAN=/bin/true make`
This skips building the manuals which helps on systems where getting
the go-md2man tool is difficult. This is similar to the trick that can be
used for PYLINT:
`PYLINT=/bin/true GO_MD2MAN=/bin/true make` now works.
=> Allow GO_MD2MAN path to be configurable via env variable

Atomic/atomic.py, atomic, docs/atomic-scan.1.md
* The openscap-daemon can now optionally take a switch
to override the behavior defined in its configuration
file as to whether to fetch new CVE input data or
not.
--fetch_cves is now a bool (True|False) where true
means to pull new, false means do not attempt
to pull aka "phone home"
* Added timeout value of 99999 to override the default dbus
connection timeout of 25 seconds.  This allows longer
scans to complete and not throw an Exception.
* Added a small def to detect a bool value based on True,
true, yes, y, 1 and so on
=> Atomic_scan: add option to override fetching of new CVE data

docs/atomic-scan.1.md
Previously the old "--no-cache" was mentioned and "fetch-cves" was used
instead of "fetch_cves".
Using --fetch-cves resulted in:
```
atomic: unrecognized arguments: --fetch-cves=False
```
=> Fixed up atomic-scan.1.md to be consistent with the fetch_cves arg

Atomic/mount.py
Atomic/mount.py
Corrects https://github.com/projectatomic/atomic/issues/186
Previously the devicemapper unmount function did
some comparisons between the pool name and the device
name to determine if the mount point being passed
to atomic was in fact a container that was mounted.  This
comparison did not work under certain conditions with
thinpool/devicemapper mounts when there was a somewhat
non-default configuration for docker-storage.
Because the atomic mount function always adds the container
ID to the device name, we can now reliably use that
and check the list of existing container IDs for a match.
=> BUG: umount not working when pool and dev names dis-similiar

Atomic/mount.py
For systems that use XFS as the docker FS, 'nouuid' needs to
be set to avoid duplicate UUID warnings when mounting
the same container or image multiple times.  XFS is the default
for RHEL7.
This also fixes the test_mount.sh failure commonly
observed on RHEL 7.
=> XFS needs 'nouuid' set

atomic
$ atomic upload
Traceback (most recent call last):
File "./atomic", line 420, in <module>
sys.exit(args.func())
File "/home/ajia/Workspace/atomic/Atomic/atomic.py", line 155, in push
if self.args.pulp:
AttributeError: 'Namespace' object has no attribute 'pulp'
=> atomic: fix 'Namespace' object has no attribute 'pulp'

Atomic/atomic.py, Atomic/util.py
Martin Preisle has found a bug that when you run atomic scan
without any values, it produces an exception.  This small
patch verifies that if neither --all, --images, --containers
is passed, then scan_targets must have at least one
argument.
=> BUGFIX: Atomic throws exception when no scan_targets are passed

Atomic/mount.py
Atomic/mount.py:
Under certain conditions, nosuid was still being
injected into the mount options.
=> XFS cannot have nosuid when mounting

Atomic/atomic.py, atomic, bash/atomic, docs/atomic-host.1.md
I just added a new `deploy` command to `rpm-ostree` in https://github.com/projectatomic/rpm-ostree/pull/178.
Here's the changes necessary to proxy it through `atomic host`.
=> Proxy new `rpm-ostree deploy` command

Makefile
Currently it is not possible to build atomic via
make without pylint. We therefore move pylint check
to separate make target
=> Make pylint check optional

Atomic/atomic.py
Docker client returns
"Cannot connect to the Docker daemon. Is the docker daemon running on this host?"
atomic info should also trigger this error.
=> Return the same message when we fail to connect to the docker daemon

Atomic/atomic.py, Atomic/mount.py, Atomic/util.py
During QE of 'atomic scan', they discovered that when scanning
of containers occurred, we frequently were left with <none>
type images.  This was because when containers are mounted, the
docker mount code actually copies (_clone, docker commit) into
a new image from which a temporary container is then made.
However, the temporary image was never removed post-processing.
While fixing this bug, I discovered two addition bugs that
needed attention.  When doing a scan, the docker mount backend
would throw an exception when trying to make a temporary
directory that already existed.
And finally, the docker mount backend would throw an exception
when it tried to work with containers that were already
mounted.  After speaking with vgoyal and given the inability to
guess what might be going on …
=> BUGFIXES: fix critical atomic scan bugs related to Mount

tests/integration/test_display.sh
This patch will get the tool to pass the tests which were
breaking because of random whitespace
=> test_display.sh should ignore whitespace.

Atomic/Export.py, Atomic/Import.py, Atomic/atomic.py, Atomic/mount.py, Atomic/pulp.py, Atomic/satellite.py, Atomic/util.py, atomic, atomic_client.py
This PR adds a pattern to the module imports used throughout the code, as suggested by PEPs 008 and 328. PEPs aside, the goal is to make it easier to tell the internal and external dependencies of each module.
Also move the urrlib3 warnings handling to the util module.
---
Change from v1 (PR #212):
- Rebased to latest master
=> Module import (re-)organization [v2]

Atomic/atomic.py, Atomic/diff.py, Atomic/mount.py, atomic, bash/atomic, docs/atomic-diff.1.md, docs/atomic.1.md
Allow users to diff between two docker images|container. There
are two types of diffs that can be run -- a file diff or an
RPM diff.  The file diff is always the default.  The RPM diff
can be added with -r.  The file diff can be excluded with -n.
=> Introduce 'atomic diff'

Atomic/diff.py
It doesn't understand native code bindings.
=> diff: Quiet pylint warning

Atomic/atomic.py
Atomic diff leaks FD when comparing images are not RPM based,
it's caused by a ValueError exception without executing clean
up work.
=> Atomic.atomic: fix FD leaks

Atomic/diff.py
rpm returns bytes for python3, need to fix encoding to printout correctly.
=> Fix output of diff to work on python3

Atomic/Export.py, Atomic/Import.py, migrate.sh, test.sh, tests/integration/test_display.sh, tests/integration/test_migrate.sh
This patch series makes some fixes so that the tests pass again.
PR #198 was merged with the tests failing. This caused the PRs that followed to also be marked as failures, thus potentially hiding any new failures. On the plus side, these failures have also helped uncover a few issues with the testing infrastructure, which should now all be resolved.
Hopefully, the auto-tester will like this PR. Once master passes again, PRs that are rebased should get a clearer picture of whether things passed or failed and why.
=> Make the tests pass

Atomic/atomic.py, Atomic/diff.py, atomic
Proposal PR to set a pattern where if an atomic subfunction
is lengthy, then we can break that out into its own class.
This reduces the overall size of the Atomic class and allows
new development and debug to be cleaner.
Instead of using the func function of argparser, we pass
the Class and Function that should be run as variables. For
example, the Atomic verify subfunction would now be:
_class=Atomic.Atomic, func='verify'
The defined class is instantiated after parseargs is run.  We
then perform the set_args and call the function.
=> Proposal: Move lengthy subfunctions to classes

Atomic/atomic.py, Atomic/top.py, atomic, bash/atomic, docs/atomic.1.md
Adding a new atomic sub-command that behaves like GNU top
but for processes being run for containers.  It currently
displays the container id,  container name,
pid, cpu% (as reported by docker
top), mem% (as reported by docker top), and the command.
You can optionally pass in -o ppid, stime, time to collect
more data on the processes themselves.
While in the interactive display, you can also sort on
the columns to re-organize the data as needed.
You can define an interval for refreshing the process
information.
atomic top can be run without any additional
parameters.  If that is the case, it will by default
show processes for all active containers.  You can also
add one or more container_ids for exclusive process
monitoring by container.
Also added an AtomicDocker class to atomic.py which …
=> Atomic TOP: Top-like display for container processes

Atomic/atomic.py, Atomic/util.py, Atomic/verify.py, atomic, docs/atomic-verify.1.md
With the remote_inspect function in RH docker, we can inspect
and image on a remote repository for various information like
versions (when present).  This allows us to expand atomic
verify to check a local version against a remote version.
atomic verify now can take an image as input (as before) and
provide a greater level of detail when checking each base
image (defined as a non-intermediate image).  It now iterates
on those base images looking for update status.
The output of atomic verify has also been changed slightly to
include a verbose option.  When invoked, the verify output
will list each base image with its versioning information.
The non-verbose output remains largely the same, where only
base images that have identified updates are put to stdout.
If verbose is not called for …
=> atomic verify: remote inspect and more details

Atomic/diff.py
Due to very small bug, the function that collects the
operating system version and RPMs was not being called.
=> Atomic Diff: RPMS arent being collected

Atomic/top.py
Fixed an indention issue which caused the process
information to be repeated several times.
=> Atomic Top: fix repeated process information

Atomic/mount.py, Atomic/verify.py, atomic
This is causing atomic unmount to fail. This searches for the DeviceName
in the list of containers to umount.
Since I was constantly typing `atomic umount` rather then `atomic unmount`,
I thought we should add an alias.
=>  In docker-1.10 the device/imageIDs are not == to container ID

test.sh
This allows users to skip all/certain tests.
```
$ sudo make test
tests all integration tests
$ sudo make test TEST_INTEGRATION=
skip all integration tests
$ sudo make test TEST_INTEGRATION='display pass'
test only the 'display' and 'pass' integration tests
```
Resolves: #259
---
This is a first step at least for integration tests, which take the longest. A `TEST_UNIT` variable could be added at a later time for similarly filtering unit tests.
=> test.sh: add TEST_INTEGRATION support

Atomic/atomic.py, atomic, docs/atomic-stop.1.md
Also allow for trailing arguments to be passed to the command in the stop label.
=> Re-enable execution of the container image stop label

Atomic/mount.py
oscap-docker on Fedora 23 failed with a MountError exception.  strace-ing the process produced the following output:
[pid 17354] execve("/sbin/dmsetup", ["dmsetup", "create", "docker-253:1-791413-c135d4b9e1cd9f68485765ed681cf80b8fe1e91559fc8a3101ecf59e35a05501", "--table", "0 20971520.0 thin /dev/mapper/vg_air-docker--pool 445"], [/* 38 vars */]) = 0
[pid 17354] +++ exited with 1 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=17354, si_uid=0, si_status=1, si_utime=0, si_stime=0} ---
Traceback (most recent call last):
File "/bin/oscap-docker", line 108, in <module>
args.func()
File "/bin/oscap-docker", line 44, in cve_scan
result = OS.scan_cve(self.args.scan_target, self.unknown_args)
File "/usr/lib/python3.4/site-packages/oscap_docker_python/oscap_docker_util.py", line 193, …
=> Pass integer to dmsetup

Atomic/verify.py
Due to a bug in atomic verify, sometimes the local and remote
versions ended up being blank.
=> Correct blank version names

Atomic/top.py
Depending on if a container has an allocated tty, you can get
different results from docker top unless you pass the -e
argument.  Adding the -e option will give correct results
regardless.
This is documented in https://bugzilla.redhat.com/show_bug.cgi?id=1293063.
=> Add -e to docker top to correct TTY issues (BZ 1293063)

Atomic/top.py, atomic, docs/atomic-top.1.md
`docker run -ti -u 1042 fedora /bin/bash` will run `/bin/bash` as user id `1042` for instance
`docker run -ti fedora /bin/bash` instead run as user id `0`
add an option to `ps_args` in `atomic top` which optionally display `UID` for the container
@baude I hope I've covered everything
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> Atomic: top: add optional uid,gid,user,group to ps_args

Atomic/util.py
With CentOS and Debian, 'makes' were failing due to a
maybe-no-member pylint error.  The error is a false
positive.  Added #pylint: disable=maybe-no-member to hush
it.
=> Atomic/util.py: Hush benign pylint error

Atomic/atomic.py
Prior to this fix, get_col_lengths() returned an error
if repo_tags was empty.  Now it returns minimal data
=> `atomic images` now handles the zero image case

Atomic/help.py, Atomic/mount.py, atomic, bash/atomic, docs/atomic-help.1.md, docs/atomic.1.md, test.sh, tests/integration/test_help.sh, tests/test-images/Dockerfile.3, tests/test-images/help.1, tests/test-images/help.sh
Images or containers can now have an associated
man-like help page to help users understand more
about the image.  Typical information included
are things like a longer description, if the image
needs to be installed, security implications, steps
to upgrade, etc.
help.py extracts help page from the image/container
and then displays it in a pager.  The default path
for the help is /image_help.1 but this can be over-
ridden with the HELP label and fully-qualified
path including the file name.
=> Atomic/help.py: Display man-like help for an image

Atomic/atomic.py
I would prefer this pull request to https://github.com/projectatomic/atomic/pull/260
Basically we want get_images to always return a list, and if the list is empty to display nothing on an
atomic images list 
command.
=> Make git_images always return a list.

Atomic/atomic.py, Atomic/run.py, atomic, bash/atomic, docs/atomic-run.1.md, tests/integration/test_help.sh
Laymen users who are told to run a image may not understand
the docker run switches that have security implications.  We
now look for the following switches:
* --privileged
* --cap-add
* --security-opt label:disable
* --net=host
* --pid=host
* --ipc=host
and output an appropriate security message.
Also, moved def run() from Atomic/atomic.py to Atomic/run.py
to reduce the size and the number of definitions in
Atomic/atomic.py.
=> Atomic/run.py: Add security implications messages based on RUN label

test.sh
Tests do not check to see if coverage is located in /usr/local/bin instead (standard on debian/ubuntu distros).
Fixes:
```
▶ sudo make test
./test.sh
Pulling standard images from Docker Hub...
Building images from tests/test-images...
Built   : atomic-test-secret
Skipped : atomic-test-3
Skipped : atomic-test-1
Skipped : atomic-test-2
UNIT TESTS:
./test.sh: line 132: /usr/bin/coverage2: No such file or directory
```
=> Check if coverage is in local bin first

Makefile
We should let `test.sh` decide whether to use bash or not, rather than `Makefile`.
Errors if not in sh / bash.
```
dropbox/dev/atomic  master ✔                                                                                                                                                                                                                              1d  
▶ sudo make test
sh ./test.sh
./test.sh: 2: set: Illegal option -o pipefail
Makefile:14: recipe for target 'test' failed
make: *** [test] Error 2
```
after PR:
```
dropbox/dev/atomic  fix-makefile ✔                                                                                                                                                                                                                        1m  
▶ sudo …
```
=> Let test.sh decide if bash, not Makefile

Atomic/run.py
I noticed at least one spacing issue on the latest el7 build in those
outputs. This patch reworks the layout of the strings so that it's
easier to read in the source code and to make sure that there are no
spacing issues.
Text is exactly the same, other than fixing spacing and changing "hosts
network" to "host's network".
=> Atomic/run.py: rewrap security helper strings

Atomic/atomic.py, Atomic/help.py, Atomic/run.py, Atomic/util.py, tests/integration/test_display.sh
Remove instances where shell=True on subprocess calls to
avoid possible exploitation.  Added def chk_call in util.py
which is similar to subp for re-use.
This addresses bugzilla 1248038.
=> atomic: harden shell invocations (1248038)

Atomic/Export.py, Atomic/atomic.py, Atomic/mount.py, Atomic/util.py
400 Client Error: Bad Request ("client is newer than server (client API version: 1.21, server API version: 1.20)")
=> use docker.AutoVersionClient to avoid API version mismatch

Atomic/atomic.py, Atomic/top.py, Atomic/util.py, Atomic/verify.py
We stopped carrying a patch in docker that allows for a RESTFUL
probe of remote registries.  This function is being replaced
by a new package called skopeo.
The remote_inspection def was removed from the Docker.Client
class extension in atomic.py and is replaced by a def called
util.skopeo which returns the same json-based results.
=> Removal of remote inspection from docker

Atomic/atomic.py
cmd_env is not a property, remove the decorator.
=> Atomic/atomic.py: Fix pylint error

Atomic/help.py
When the cmd_env defition had its property decorator removed,
a single call to cmd_env in help.py was missed.
=> Atomic/help.py: cmd_env no longer a property

Atomic/Export.py, Atomic/atomic.py, Atomic/client.py, Atomic/mount.py, Atomic/top.py, Atomic/util.py
All uses of docker.Client() (docker-py) now should be using
the DockerClient definition in client.py.  Any changes to the
client instantiation or function can now be changed in a
singular location.
Also, the DockerClient function has a fallback from
docker.AutoVersionClient to docker.Client using a try and
except condition.  This fixes an issue raised in:
https://github.com/projectatomic/atomic/issues/302
where atomic cannot be built due to imports when dockerd is not
running.
=> Atomic/client.py: Universal method for docker.Client()

Atomic/atomic.py, Atomic/util.py, Atomic/verify.py
In the case where an image was tagged more than once, atomic
verify would sometimes resolve the wrong fully qualified name
due to an ordering issue in one of the supporting functions.
=> Fix verify where an image is tagged more than once

Atomic/verify.py, tests/test-images/Dockerfile.4
Added a test case to test for failure when an image has
multiple repotags and is asked to be verified by image
id.  This should result in a failure.
Also, turned verify debug off.
=> Add test for atomic verify

Atomic/atomic.py, Atomic/mount.py, Atomic/top.py, Atomic/util.py, atomic
In the case where the docker daemon is not running, each
Atomic subcommand was returning a different error message. This
PR unifies the errors messages for each subcommand.
This work was done for Bugzilla #1300187
=> Unify error messages for no docker daemon (BZ #1300187)

Atomic/diff.py
When an RPM diff was performed between two docker objects, we
previously only store the name, version, and epoch of the RPM for
comparision.  It turns out versioning information is also done in
the release portion as well.
This addresses https://github.com/projectatomic/atomic/issues/315
=> Atomic/diff.py Add release to version, name, and epoch of RPM

Atomic/atomic.py, Atomic/util.py
In python-docker-py-1.6, the error handling improved
significantly.  When a docker object cannot be found,
say with client.inspect(), it now throws a specific
exception called NotFound instead of the old, generic
Docker error.  We have now updated some of our functions
to use the specific error because it was 'covering' other
docker client failures such as API compatibilies.
Also added a new custom Error class to handle a common
error message we used repeatidly.  The new class is
called 'DockerObjectNotFound' and will output a
consistent messages and takes the dockerobject as input.
This is most commonly used when we verify the users'
input for validity and is different that the docker
client NotFound error.
=> Improve error handling with the docker-py client

Atomic/top.py, Makefile
This also should replace https://github.com/projectatomic/atomic/pull/323
=> Fixes for running atomic on python3

setup.py
This is a minor fix for coding conventions.
=> Coding Convention: E251 unexpected spaces around keyword / parameter equals

Atomic/atomic.py, Atomic/verify.py, tests/integration/test_info.sh
We now use the fully qualified image name (if not provided)
when dealing with atomic info and verify.  This is because
skopeo requires a fq image name to do remote inspection. As
an upside, it also makes atomic a little more user friendly
as well.
=> Use fully-qualified image name in info() and verify()

Atomic/atomic.py, atomic, bash/atomic, docs/atomic-host.1.md
It's nicer for branding the command.  The more correct thing would be
to add it to the rpm-ostree daemon and pass through there, but we have
more important problems to fix for the production code path.  This is
just for local development, so the slightly dirty way is just fine.
=> host: Pass through unlock -> ostree admin unlock

Atomic/util.py
Prior to dropping shell=true, shell expansion on run/install/uninstall was
working, now we break in the case of a command like
LABEL INSTALL 'bash -c "echo foo foo foo"'
Adding shlex.split rather then standard split will break this command into
['bash', '-c', '"echo foo foo foo"']
Which will be executed correctly.
=> Fix shell expansion on commands.

Atomic/top.py
Using self.ping(), we now check to make sure the docker
daemon is running before executing any code to display
atomic top.
This fixes a followup bug reported in:
https://bugzilla.redhat.com/show_bug.cgi?id=1300187#c5
=> Atomic/top.py Make sure dockerd is running

Atomic/atomic.py, Atomic/scan.py, Atomic/util.py, Makefile, atomic, atomic.conf, atomic.d/openscap, docs/atomic.1.md
As more scanners besides openscap become available, atomic
can now begin to leverage them.  The new scan function has
been broken out into its on file (scan.py).
The scan command itself now defaults to openscap but can
also be switched to blackduck with --scanner.
Atomic now can use a configuration file which is stored
in /etc/atomic.conf.  In the case of the scan function,
we need the scanner defined in the configuration file
as well as the fully qualified image name and the
scan arguments.  Optionally, you can provide additional
custom docker arguments for the scanner as well
=> Implement generic scanning in Atomic

Atomic/scan.py, atomic
Added the ability to define custom docker args in the plugin
configuration files for things like bind mounting dirs from
the host to the scanner image.
When parsing the atomic scan json files, we can now handle
'Vulnerabilities' or 'Results' for keys.
Added a --debug switch to the base atomic command to allow for
more specifics when an unwanted exception is raised.
Fixed minor bug where if no image/container is provided, the
scanner would still execute.
=> Atomic/scan.py: Custom docker args

Atomic/scan.py
In the case where an unknown scanner is defined as the default in
/etc/atomic.conf, we need to catch that as an error and raise it
to the user.
=> Atomic/scan.py: Catch unknown default scanner

Atomic/Export.py, Atomic/Import.py, Atomic/__init__.py, Atomic/atomic.py, Atomic/diff.py, Atomic/help.py, Atomic/pulp.py, Atomic/run.py, Atomic/satellite.py, Atomic/satellite_new.py.test, Atomic/scan.py, Atomic/top.py, Atomic/util.py, Atomic/verify.py, Makefile, atomic, atomic.conf, bash/atomic, dockertar-sha256-helper.go, docs/atomic-install.1.md, docs/atomic-pull.1.md, docs/atomic-update.1.md, requirements.txt, tests/integration/test_dockertar_sha256_helper.sh
these patches are the current status of system containers.  There are a few things missing on Atomic Host before this feature can be used:
- skopeo
- runc
- python3-gobject-base
For an idea of how they work, I prepared a demo here: https://asciinema.org/a/40300
=> [RFC] System containers

Atomic/scan.py, atomic.d/openscap
When conducting a compliance scan, we do not want to check CVES
as that is done by the default scan.
=> atomic.d/openscap: Do standard compliance scan without CVEs

Atomic/atomic.py, Atomic/util.py, Atomic/verify.py
the same function used by system containers is used by verify (retrieve a manifest through Skopeo), so I refactored this part in common in util.py.
While I was at it, I also changed verify.py to use a newer Skopeo version
=> Refactor skopeo code

Atomic/verify.py
This reverts a portion of d28fcbbf49023550953aece098ad86146dec1385 where the
iterators were accidently changed to a Python 3 implementation.
=> Atomic/verify.py: Make iterator work on Python2 and 3

atomic
Certain subcommands like diff and scan require root auth
to work correctly.  Added an except clause to catch the
permission denied errors.
=> atomic: Handle subcommands that require root auth

Atomic/atomic.py
When self.args.container was not defined, the update() def
was failing.  Fixed the conditional to check if self.args.container
exists first.
This failure would make an atomic install <image> fail when the
image was not locally present.
=> Atomic/atomic.py: Fix def update()

Atomic/scan.py, atomic
When atomic scan needs to create the output directories, it needs to
do this recursively in case they don't already exist.  Changed from
os.mkdir to os.makedirs to handle this.
=> Atomic/scan.py, atomic: Fix scan related errors

atomic
When calling atomic or atomic <subcommand> with the
--help switch, we expose a NameError exception because
args is not evidently parsed for displaying of help. I
added a conditional to make sure the args variable exists
before using it.
=> atomic: Fix NameError when calling with --help

Atomic/atomic.py
The manifest was not stored correctly after commit
052be75598285205b308bbd181ffd314b3fbd78a.
=> atomic: fix import of Docker images

Atomic/util.py
The check takes care of it, but python3-pylint is not smart enough to
catch this.
=> python3-pylint blows up on this undefined variable

Atomic/atomic.py, tests/integration/test_printenv.sh
On certain systems loginuid might not be set which could give a value of
4294967295
docker will not allow users > 2147483647, if you loginuid is -1 it ends up
being bigger
SUDO_UID and SUDO_GID, not always defined in environment
=> A couple of testing fixes

Atomic/atomic.py, atomic, bash/atomic, docs/atomic-images.1.md
In certain cases like piping to grep, you do not want to include headings
=> Add atomic images --noheading

Atomic/atomic.py
By passing "--name" and not passing "--rm".
=> run: Make "--spc" consistent with the other cases

Atomic/run.py
It might be docker-latest.
This depends on #431
=> run: Substitute actual docker binary in RUN label

Atomic/atomic.py
If given image name is included repository list use it.
This change allows the following workflow:
```
$ docker pull kubernetes/pause
$ docker tag kubernetes/pause localhost:5000/my/pause
$ docker push localhost:5000/my/pause
$ atomic info localhost:5000/kubernetes/pause:latest
```
Signed-off-by: Jhon Honce <jhonce@redhat.com>
=> If given image name is included repository list use it.

Atomic/scan.py
`atomic scan fedora:24` runs `docker -it ...` and it needs to have interactive terminal.
Consequences: `atomic scan fedora:24` is not usable in cases like
- `nohup atomic scan fedora:24`
- `ssh root@localhost atomic scan fedora:24`
- ...
It only prints `cannot enable tty mode on non tty input`.
=> Atomic/scan.py: Don't keep open STDIN for scan

Atomic/atomic.py, Atomic/syscontainers.py, atomic, bash/atomic, docs/atomic-pull.1.md, tests/unit/test_pull.py
Atomic now has --user flag which creates a BARE_USER repo locally to allow non-privileged user to pull images.
=> Atomic now has --user flag.

Atomic/backends/_docker.py, Atomic/backends/_ostree.py, Atomic/backends/backend.py, Atomic/backendutils.py, Atomic/containers.py, Atomic/delete.py, Atomic/discovery.py, Atomic/images.py, Atomic/info.py, Atomic/objects/image.py, Atomic/run.py, Atomic/syscontainers.py, Atomic/update.py, Atomic/util.py, Atomic/verify.py, bash/atomic
Disconnect backends
Ideally, the atomic CLI should be able to operate independently
of the backends it supports.  For example, if dockerd is inactive,
the ostree backend and atomic cli should still work.
This requires some tweaking to the backendutils code and the work
flow.  We also need to specifically know if the user passes
--storage so that we treat that as an explicit override.  The work
flow is now roughly:
* a default storage can be defined in atomic.conf (was always this way)
* if not defined, defaults to docker.
* if --storage is passed, treat explictly and fail if cannot execute
* if no --storage is specified, use default.  if default is not available, move
onto the next backend
=> Backend missing

Atomic/mount.py
Instead of using the hardcoded path to /var/lib/[docker, docker-latest],
we should use the helper method default_docker_lib() in util.  This
should allow overlay2 to work with both mount and scan.
=> Atomic/mount.py: Use default_docker_lib()

Atomic/util.py
Fix a cirucular dependancy in atomic storage reset where certain
functions require a dockerd but storage reset requires dockerd to
be stopped.
=> Atomic/util.py Fix Try/Catch exceptions for dockerd

docs/install/Debian.md, requirements.txt
Fix building issue on Debian with @ashcrow 
Add some requirements and remove deprecated ones.
-
-
- #1118 
If your Pull request contains new features or functions, tests are required. If the PR is a bug fix and no tests exist, please consider adding some to prevent regressions.
=> Fix building issue on Debian

Atomic/util.py
if skopeo doesn't include "msg=" in its error message, atomic fails
returning the wrong message.
Easily reproducible with:
SKOPEO_PATH=/bin/false atomic run foo
=> util: ensure SkopeoError has msg

Atomic/syscontainers.py
Images coming from registry.access.redhat.com through "skopeo copy"
have this information in the v1Compatibility block.  Use this
information so we can correctly catch "atomic.run".
=> syscontainers: read labels from v1Compatibility

Atomic/util.py
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1583731
=> util: if the Skopeo error is empty, print the full stderr
